// Code generated by counterfeiter. DO NOT EDIT.
package fritzboxfakes

import (
	"home-gate/internal/fritzbox"
	"sync"
)

type FakeClient struct {
	BlockDeviceStub        func(string, bool) error
	blockDeviceMutex       sync.RWMutex
	blockDeviceArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	blockDeviceReturns struct {
		result1 error
	}
	blockDeviceReturnsOnCall map[int]struct {
		result1 error
	}
	ConnectStub        func() error
	connectMutex       sync.RWMutex
	connectArgsForCall []struct {
	}
	connectReturns struct {
		result1 error
	}
	connectReturnsOnCall map[int]struct {
		result1 error
	}
	GetLandevicesStub        func() ([]fritzbox.Landevice, error)
	getLandevicesMutex       sync.RWMutex
	getLandevicesArgsForCall []struct {
	}
	getLandevicesReturns struct {
		result1 []fritzbox.Landevice
		result2 error
	}
	getLandevicesReturnsOnCall map[int]struct {
		result1 []fritzbox.Landevice
		result2 error
	}
	GetMonitorConfigStub        func() (fritzbox.MonitorConfig, error)
	getMonitorConfigMutex       sync.RWMutex
	getMonitorConfigArgsForCall []struct {
	}
	getMonitorConfigReturns struct {
		result1 fritzbox.MonitorConfig
		result2 error
	}
	getMonitorConfigReturnsOnCall map[int]struct {
		result1 fritzbox.MonitorConfig
		result2 error
	}
	GetMonitorDataStub        func(string, string) ([]fritzbox.SubsetData, error)
	getMonitorDataMutex       sync.RWMutex
	getMonitorDataArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getMonitorDataReturns struct {
		result1 []fritzbox.SubsetData
		result2 error
	}
	getMonitorDataReturnsOnCall map[int]struct {
		result1 []fritzbox.SubsetData
		result2 error
	}
	GetMonitorDatasetsStub        func() ([]fritzbox.Dataset, error)
	getMonitorDatasetsMutex       sync.RWMutex
	getMonitorDatasetsArgsForCall []struct {
	}
	getMonitorDatasetsReturns struct {
		result1 []fritzbox.Dataset
		result2 error
	}
	getMonitorDatasetsReturnsOnCall map[int]struct {
		result1 []fritzbox.Dataset
		result2 error
	}
	RestGetStub        func(string) ([]byte, int, error)
	restGetMutex       sync.RWMutex
	restGetArgsForCall []struct {
		arg1 string
	}
	restGetReturns struct {
		result1 []byte
		result2 int
		result3 error
	}
	restGetReturnsOnCall map[int]struct {
		result1 []byte
		result2 int
		result3 error
	}
	SIDStub        func() string
	sIDMutex       sync.RWMutex
	sIDArgsForCall []struct {
	}
	sIDReturns struct {
		result1 string
	}
	sIDReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) BlockDevice(arg1 string, arg2 bool) error {
	fake.blockDeviceMutex.Lock()
	ret, specificReturn := fake.blockDeviceReturnsOnCall[len(fake.blockDeviceArgsForCall)]
	fake.blockDeviceArgsForCall = append(fake.blockDeviceArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	stub := fake.BlockDeviceStub
	fakeReturns := fake.blockDeviceReturns
	fake.recordInvocation("BlockDevice", []interface{}{arg1, arg2})
	fake.blockDeviceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) BlockDeviceCallCount() int {
	fake.blockDeviceMutex.RLock()
	defer fake.blockDeviceMutex.RUnlock()
	return len(fake.blockDeviceArgsForCall)
}

func (fake *FakeClient) BlockDeviceCalls(stub func(string, bool) error) {
	fake.blockDeviceMutex.Lock()
	defer fake.blockDeviceMutex.Unlock()
	fake.BlockDeviceStub = stub
}

func (fake *FakeClient) BlockDeviceArgsForCall(i int) (string, bool) {
	fake.blockDeviceMutex.RLock()
	defer fake.blockDeviceMutex.RUnlock()
	argsForCall := fake.blockDeviceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) BlockDeviceReturns(result1 error) {
	fake.blockDeviceMutex.Lock()
	defer fake.blockDeviceMutex.Unlock()
	fake.BlockDeviceStub = nil
	fake.blockDeviceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) BlockDeviceReturnsOnCall(i int, result1 error) {
	fake.blockDeviceMutex.Lock()
	defer fake.blockDeviceMutex.Unlock()
	fake.BlockDeviceStub = nil
	if fake.blockDeviceReturnsOnCall == nil {
		fake.blockDeviceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.blockDeviceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Connect() error {
	fake.connectMutex.Lock()
	ret, specificReturn := fake.connectReturnsOnCall[len(fake.connectArgsForCall)]
	fake.connectArgsForCall = append(fake.connectArgsForCall, struct {
	}{})
	stub := fake.ConnectStub
	fakeReturns := fake.connectReturns
	fake.recordInvocation("Connect", []interface{}{})
	fake.connectMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) ConnectCallCount() int {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	return len(fake.connectArgsForCall)
}

func (fake *FakeClient) ConnectCalls(stub func() error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = stub
}

func (fake *FakeClient) ConnectReturns(result1 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	fake.connectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) ConnectReturnsOnCall(i int, result1 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	if fake.connectReturnsOnCall == nil {
		fake.connectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.connectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) GetLandevices() ([]fritzbox.Landevice, error) {
	fake.getLandevicesMutex.Lock()
	ret, specificReturn := fake.getLandevicesReturnsOnCall[len(fake.getLandevicesArgsForCall)]
	fake.getLandevicesArgsForCall = append(fake.getLandevicesArgsForCall, struct {
	}{})
	stub := fake.GetLandevicesStub
	fakeReturns := fake.getLandevicesReturns
	fake.recordInvocation("GetLandevices", []interface{}{})
	fake.getLandevicesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetLandevicesCallCount() int {
	fake.getLandevicesMutex.RLock()
	defer fake.getLandevicesMutex.RUnlock()
	return len(fake.getLandevicesArgsForCall)
}

func (fake *FakeClient) GetLandevicesCalls(stub func() ([]fritzbox.Landevice, error)) {
	fake.getLandevicesMutex.Lock()
	defer fake.getLandevicesMutex.Unlock()
	fake.GetLandevicesStub = stub
}

func (fake *FakeClient) GetLandevicesReturns(result1 []fritzbox.Landevice, result2 error) {
	fake.getLandevicesMutex.Lock()
	defer fake.getLandevicesMutex.Unlock()
	fake.GetLandevicesStub = nil
	fake.getLandevicesReturns = struct {
		result1 []fritzbox.Landevice
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetLandevicesReturnsOnCall(i int, result1 []fritzbox.Landevice, result2 error) {
	fake.getLandevicesMutex.Lock()
	defer fake.getLandevicesMutex.Unlock()
	fake.GetLandevicesStub = nil
	if fake.getLandevicesReturnsOnCall == nil {
		fake.getLandevicesReturnsOnCall = make(map[int]struct {
			result1 []fritzbox.Landevice
			result2 error
		})
	}
	fake.getLandevicesReturnsOnCall[i] = struct {
		result1 []fritzbox.Landevice
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetMonitorConfig() (fritzbox.MonitorConfig, error) {
	fake.getMonitorConfigMutex.Lock()
	ret, specificReturn := fake.getMonitorConfigReturnsOnCall[len(fake.getMonitorConfigArgsForCall)]
	fake.getMonitorConfigArgsForCall = append(fake.getMonitorConfigArgsForCall, struct {
	}{})
	stub := fake.GetMonitorConfigStub
	fakeReturns := fake.getMonitorConfigReturns
	fake.recordInvocation("GetMonitorConfig", []interface{}{})
	fake.getMonitorConfigMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetMonitorConfigCallCount() int {
	fake.getMonitorConfigMutex.RLock()
	defer fake.getMonitorConfigMutex.RUnlock()
	return len(fake.getMonitorConfigArgsForCall)
}

func (fake *FakeClient) GetMonitorConfigCalls(stub func() (fritzbox.MonitorConfig, error)) {
	fake.getMonitorConfigMutex.Lock()
	defer fake.getMonitorConfigMutex.Unlock()
	fake.GetMonitorConfigStub = stub
}

func (fake *FakeClient) GetMonitorConfigReturns(result1 fritzbox.MonitorConfig, result2 error) {
	fake.getMonitorConfigMutex.Lock()
	defer fake.getMonitorConfigMutex.Unlock()
	fake.GetMonitorConfigStub = nil
	fake.getMonitorConfigReturns = struct {
		result1 fritzbox.MonitorConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetMonitorConfigReturnsOnCall(i int, result1 fritzbox.MonitorConfig, result2 error) {
	fake.getMonitorConfigMutex.Lock()
	defer fake.getMonitorConfigMutex.Unlock()
	fake.GetMonitorConfigStub = nil
	if fake.getMonitorConfigReturnsOnCall == nil {
		fake.getMonitorConfigReturnsOnCall = make(map[int]struct {
			result1 fritzbox.MonitorConfig
			result2 error
		})
	}
	fake.getMonitorConfigReturnsOnCall[i] = struct {
		result1 fritzbox.MonitorConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetMonitorData(arg1 string, arg2 string) ([]fritzbox.SubsetData, error) {
	fake.getMonitorDataMutex.Lock()
	ret, specificReturn := fake.getMonitorDataReturnsOnCall[len(fake.getMonitorDataArgsForCall)]
	fake.getMonitorDataArgsForCall = append(fake.getMonitorDataArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetMonitorDataStub
	fakeReturns := fake.getMonitorDataReturns
	fake.recordInvocation("GetMonitorData", []interface{}{arg1, arg2})
	fake.getMonitorDataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetMonitorDataCallCount() int {
	fake.getMonitorDataMutex.RLock()
	defer fake.getMonitorDataMutex.RUnlock()
	return len(fake.getMonitorDataArgsForCall)
}

func (fake *FakeClient) GetMonitorDataCalls(stub func(string, string) ([]fritzbox.SubsetData, error)) {
	fake.getMonitorDataMutex.Lock()
	defer fake.getMonitorDataMutex.Unlock()
	fake.GetMonitorDataStub = stub
}

func (fake *FakeClient) GetMonitorDataArgsForCall(i int) (string, string) {
	fake.getMonitorDataMutex.RLock()
	defer fake.getMonitorDataMutex.RUnlock()
	argsForCall := fake.getMonitorDataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) GetMonitorDataReturns(result1 []fritzbox.SubsetData, result2 error) {
	fake.getMonitorDataMutex.Lock()
	defer fake.getMonitorDataMutex.Unlock()
	fake.GetMonitorDataStub = nil
	fake.getMonitorDataReturns = struct {
		result1 []fritzbox.SubsetData
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetMonitorDataReturnsOnCall(i int, result1 []fritzbox.SubsetData, result2 error) {
	fake.getMonitorDataMutex.Lock()
	defer fake.getMonitorDataMutex.Unlock()
	fake.GetMonitorDataStub = nil
	if fake.getMonitorDataReturnsOnCall == nil {
		fake.getMonitorDataReturnsOnCall = make(map[int]struct {
			result1 []fritzbox.SubsetData
			result2 error
		})
	}
	fake.getMonitorDataReturnsOnCall[i] = struct {
		result1 []fritzbox.SubsetData
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetMonitorDatasets() ([]fritzbox.Dataset, error) {
	fake.getMonitorDatasetsMutex.Lock()
	ret, specificReturn := fake.getMonitorDatasetsReturnsOnCall[len(fake.getMonitorDatasetsArgsForCall)]
	fake.getMonitorDatasetsArgsForCall = append(fake.getMonitorDatasetsArgsForCall, struct {
	}{})
	stub := fake.GetMonitorDatasetsStub
	fakeReturns := fake.getMonitorDatasetsReturns
	fake.recordInvocation("GetMonitorDatasets", []interface{}{})
	fake.getMonitorDatasetsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetMonitorDatasetsCallCount() int {
	fake.getMonitorDatasetsMutex.RLock()
	defer fake.getMonitorDatasetsMutex.RUnlock()
	return len(fake.getMonitorDatasetsArgsForCall)
}

func (fake *FakeClient) GetMonitorDatasetsCalls(stub func() ([]fritzbox.Dataset, error)) {
	fake.getMonitorDatasetsMutex.Lock()
	defer fake.getMonitorDatasetsMutex.Unlock()
	fake.GetMonitorDatasetsStub = stub
}

func (fake *FakeClient) GetMonitorDatasetsReturns(result1 []fritzbox.Dataset, result2 error) {
	fake.getMonitorDatasetsMutex.Lock()
	defer fake.getMonitorDatasetsMutex.Unlock()
	fake.GetMonitorDatasetsStub = nil
	fake.getMonitorDatasetsReturns = struct {
		result1 []fritzbox.Dataset
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetMonitorDatasetsReturnsOnCall(i int, result1 []fritzbox.Dataset, result2 error) {
	fake.getMonitorDatasetsMutex.Lock()
	defer fake.getMonitorDatasetsMutex.Unlock()
	fake.GetMonitorDatasetsStub = nil
	if fake.getMonitorDatasetsReturnsOnCall == nil {
		fake.getMonitorDatasetsReturnsOnCall = make(map[int]struct {
			result1 []fritzbox.Dataset
			result2 error
		})
	}
	fake.getMonitorDatasetsReturnsOnCall[i] = struct {
		result1 []fritzbox.Dataset
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) RestGet(arg1 string) ([]byte, int, error) {
	fake.restGetMutex.Lock()
	ret, specificReturn := fake.restGetReturnsOnCall[len(fake.restGetArgsForCall)]
	fake.restGetArgsForCall = append(fake.restGetArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RestGetStub
	fakeReturns := fake.restGetReturns
	fake.recordInvocation("RestGet", []interface{}{arg1})
	fake.restGetMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeClient) RestGetCallCount() int {
	fake.restGetMutex.RLock()
	defer fake.restGetMutex.RUnlock()
	return len(fake.restGetArgsForCall)
}

func (fake *FakeClient) RestGetCalls(stub func(string) ([]byte, int, error)) {
	fake.restGetMutex.Lock()
	defer fake.restGetMutex.Unlock()
	fake.RestGetStub = stub
}

func (fake *FakeClient) RestGetArgsForCall(i int) string {
	fake.restGetMutex.RLock()
	defer fake.restGetMutex.RUnlock()
	argsForCall := fake.restGetArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) RestGetReturns(result1 []byte, result2 int, result3 error) {
	fake.restGetMutex.Lock()
	defer fake.restGetMutex.Unlock()
	fake.RestGetStub = nil
	fake.restGetReturns = struct {
		result1 []byte
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) RestGetReturnsOnCall(i int, result1 []byte, result2 int, result3 error) {
	fake.restGetMutex.Lock()
	defer fake.restGetMutex.Unlock()
	fake.RestGetStub = nil
	if fake.restGetReturnsOnCall == nil {
		fake.restGetReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 int
			result3 error
		})
	}
	fake.restGetReturnsOnCall[i] = struct {
		result1 []byte
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) SID() string {
	fake.sIDMutex.Lock()
	ret, specificReturn := fake.sIDReturnsOnCall[len(fake.sIDArgsForCall)]
	fake.sIDArgsForCall = append(fake.sIDArgsForCall, struct {
	}{})
	stub := fake.SIDStub
	fakeReturns := fake.sIDReturns
	fake.recordInvocation("SID", []interface{}{})
	fake.sIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) SIDCallCount() int {
	fake.sIDMutex.RLock()
	defer fake.sIDMutex.RUnlock()
	return len(fake.sIDArgsForCall)
}

func (fake *FakeClient) SIDCalls(stub func() string) {
	fake.sIDMutex.Lock()
	defer fake.sIDMutex.Unlock()
	fake.SIDStub = stub
}

func (fake *FakeClient) SIDReturns(result1 string) {
	fake.sIDMutex.Lock()
	defer fake.sIDMutex.Unlock()
	fake.SIDStub = nil
	fake.sIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeClient) SIDReturnsOnCall(i int, result1 string) {
	fake.sIDMutex.Lock()
	defer fake.sIDMutex.Unlock()
	fake.SIDStub = nil
	if fake.sIDReturnsOnCall == nil {
		fake.sIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.sIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fritzbox.Client = new(FakeClient)
